-- WARNING: Do NOT edit the input and output ports in this file in a text
-- editor if you plan to continue editing the block that represents it in
-- the Block Editor! File corruption is VERY likely to occur.

-- Copyright (C) 1991-2005 Altera Corporation
-- Your use of Altera Corporation's design tools, logic functions 
-- and other software and tools, and its AMPP partner logic       
-- functions, and any output files any of the foregoing           
-- (including device programming or simulation files), and any    
-- associated documentation or information are expressly subject  
-- to the terms and conditions of the Altera Program License      
-- Subscription Agreement, Altera MegaCore Function License       
-- Agreement, or other applicable license agreement, including,   
-- without limitation, that your use is for the sole purpose of   
-- programming logic devices manufactured by Altera and sold by   
-- Altera or its authorized distributors.  Please refer to the    
-- applicable agreement for further details.


-- Generated by Quartus II Version 5.0 (Build Build 168 06/22/2005)
-- Created on Wed Aug 31 13:20:23 2005

LIBRARY ieee;
USE ieee.std_logic_1164.all;
use IEEE.STD_LOGIC_UNSIGNED.ALL;


--  Entity Declaration

ENTITY Sync_Len IS
	GENERIC (	-- Initial SL Value on Reset, comment out all but 1 of the following
--			SL_CNT      : STD_LOGIC_VECTOR := X"00000"	-- 00
			SL_CNT      : STD_LOGIC_VECTOR := X"00A40"	-- = NR 41, RL 64, = SL 2624; default for SC2
--			SL_CNT      : STD_LOGIC_VECTOR := X"00063"	-- = 100
			);


	-- {{ALTERA_IO_BEGIN}} DO NOT REMOVE THIS LINE!
	PORT
	(
		Clk25M 		: IN STD_LOGIC;
		SL_Load 	: IN STD_LOGIC;	-- active high input
		CmdData 	: IN STD_LOGIC_VECTOR(31 downto 0);
		Reset 		: IN STD_LOGIC;	-- active low input
		Enable 		: IN STD_LOGIC;	-- active high input
		DV_Error 	: IN STD_LOGIC;	-- active high input, not used 
		isAddr_Zero : OUT STD_LOGIC	-- active low output
		
		-- sim & test o/p; else comment out
--		SLCntr_o	: OUT STD_LOGIC_VECTOR(19 DOWNTO 0) 
	);
	-- {{ALTERA_IO_END}} DO NOT REMOVE THIS LINE!
	
END Sync_Len ;


--  Architecture Body

ARCHITECTURE V3c OF Sync_Len IS

	signal SL_LoadReg	: STD_LOGIC_VECTOR(19 DOWNTO 0);  -- preset input of counter.
	signal SLCntr		: STD_LOGIC_VECTOR(19 DOWNTO 0); 
	
BEGIN

	-- sim & test o/p; else comment out
--	SLCntr_o <= SLCntr;
	
dwncnt: process (Reset, Clk25M, Enable) 
	begin
	if  (Reset = '0' ) then
		SL_LoadReg 	<= SL_CNT; 	
		SLCntr 		<= X"00000";
		isAddr_Zero <= '1';
	
	elsif (rising_edge(Clk25M)) then
	
		if (SL_Load = '1') then 
			SL_LoadReg <= CmdData(19 downto 0);
		else 
			SL_LoadReg <= SL_LoadReg; 
		end if;
		
		if (Enable = '1' AND SL_LoadReg /= X"00000") then 
			if (SLCntr = X"00000" ) then
				isAddr_Zero <= '0';
				SLCntr <= SL_LoadReg; 
			else
				isAddr_Zero <= '1';
				SLCntr <= SLCntr - 1; 
			end if; 
		end if;
		 
	end if; 
	
end process dwncnt;
	
END V3c;